ans-graceshopper/spell-store

server/db/models/spell.js
server/db/models/user.js

defined product model

---

server/seed/fakeData.json
server/seed/seed.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

added fakeData

---

server/db/models/user.js

added isEmail validate for user model

updated email in user model

---

server/db/models/user.js

Users model #5

---

server/db/models/index.js
server/db/models/order.js
server/db/models/review.js
server/db/models/spell.js

Review model #10

---

server/db/models/index.js
server/db/models/order.js
server/db/models/spell.js

Started Order model and added associations

Orders model #18

---

package.json

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

-line16 package.json

---

client/components/navbar.js
public/index.html

Changed boilermaker text to spell binder

updated header to spell binder

---

client/components/addSpell.js
client/components/allspells.js
client/components/index.js
client/components/spellform.js
client/routes.js
client/store/spell.js
server/api/spells.js
server/db/db.js

Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_

added form, post route works, need to make form dumb

---

client/components/allspells.js
client/components/navbar.js
client/components/spell.js
script/seed.js
server/db/models/user.js

hacky, unsecured admin functionality!

Admin stuff

---

server/api/spells.js
server/db/models/order.js
server/db/models/review.js
server/db/models/spell.js
server/index.js

added notes as comments in relevant files

added notes from code review

---

server/db/models/spell.spec.js

some are failing, this is not a mistake and must be fixed! npm run test will run the tests for you

added tests for spell model

---

package.json
server/db/models/index.js
server/db/models/order.js
server/db/models/spell.js
server/db/models/spell.spec.js
server/db/models/spellorders.js

I did things. they're in the commit message.

Order model routes#44

---

server/db/models/order.js

Removed extraneous price from Order model

removed extra price from order model

---

client/store/cart.js
client/store/index.js
server/db/models/spell.js

Spell model edit

---

client/store/cart.js
client/store/index.js

added cart redux functionality

simple cart reducer

---

server/api/cart.js
server/api/index.js
server/api/spells.js
server/api/users.js
server/db/models/order.js

Cart routes #58

---

script/seed.js
server/db/models/index.js
server/db/models/spellorders.js

Orders users seeds #62

---

script/seed.js

can't use 0 index, switched seed to spell at 1 index

fixed through table error

---

script/seed.js
server/api/cart.spec.js
server/api/review.spec.js
server/api/spells.js
server/db/models/review.js

updated review model and more

---

client/components/user-home.js
client/routes.js
client/store/user.js
script/seed.js
server/auth/index.js
server/index.js

- only works when freshly logged in, session is not persisting 
- could be reorganized

User home prev orders#80

---

client/components/spelldetail.js
server/api/cart.js

it was so simple! not that it really works yet.

Unauth user cart #85

---

client/components/lineItem.js
server/api/cart.js
server/db/models/index.js
server/db/models/spellorders.spec.js

unfinished tests

---

client/components/allspells.js

Added search box that works with existing filters.
Added "View All" button that clears any filters.
(also extra divs for CSS that will come soon)

added search box and view all button to clear filters

---

client/store/cart.js
server/api/cart.js

updated reducer, cart routes slightly. still not working: remove from cart as logged out user. will continue working on this branch! but it will be useful to actually have a working cart, and so, this pull request was made

Cart api routes

---

server/api/index.js
server/api/orders.js

Created new API route for orders, to be used by admins to view all orders, and should update existing order history vertical slice to request orders by user id from this new orders route file.

Orders routes #100

---

client/store/index.js
client/store/order.js

Created orders reducer to use for admin dashboard.

Orders reducer #101

---

client/components/index.js
client/components/navbar.js
client/components/user-account.js
client/components/user-order-detail.js
client/components/user-order-lineitem.js
client/components/user-order-list.js
client/components/user-orders.js
client/routes.js
client/store/user.js
public/style.css

added user management tools and started thunk functions 
- user models will need to be updated to include firstName, lastName, imageUrl, etc. for now they are blank in the form. 
for user order details, for some reason orders no longer include spell array. I will track this down and figure it out.

added user account management tools

---

client/components/spelldetail.js
client/components/user-order-detail.js
client/components/user-order-lineitem.js
client/components/user-order-list.js
client/components/user-orders.js
client/store/index.js
client/store/order-spells.js
client/store/order.js
client/store/spell-detail.js
client/store/spell.js
client/store/user-orders.js
client/store/user.js
server/api/orders.js
server/api/spells.js
server/api/users.js
server/db/models/order.js

Updated spell and order detail vertical slices

Spell detail

---

client/app.js
client/components/Checkout.js
client/components/cart.js
package-lock.json
package.json
public/index.html
server/api/index.js
server/api/stripe.js
server/index.js

rudimentary stripe integration done?

---

client/components/Checkout.js
server/db/models/order.js
server/db/models/spell.js

Added total to order model and adjusted stripe amount data format

Price updates #120

---

client/components/admin-order-lineitem.js
client/components/admin-order-list.js
client/components/allorders.js
client/components/navbar.js
client/routes.js

- admin-order-list shows all orders including the user
- all orders lists all orders
- navbar now includes admin link
- client/routes includes a path for admins to view all order

Admin routes

---

client/components/Checkout.js
client/components/cart.js
client/components/user-order-detail.js

various small bug fixes / updates

Last bug fixes

---

client/components/Checkout.js
client/components/cart.js
client/components/lineItem.js
client/store/cart.js
server/api/stripe.js

Reverts ans-graceshopper/spell-store#132

Revert "on checkout, deducts quantity from inventory and adds total order $$ …"

---

client/components/Checkout.js
client/components/cart.js
client/components/lineItem.js
client/store/cart.js
server/api/stripe.js

Reverts ans-graceshopper/spell-store#133 PUT IT BACK AGAIN

Revert "Revert "on checkout, deducts quantity from inventory and adds total order $$ …""

---

client/components/cart.js
server/api/orders.js
server/auth/index.js

cart now is created upon login if there is a req.session.cart!

forced user to create account on checkout and persisted their cart!

---

client/components/allspells.js
client/components/index.js
client/store/index.js
script/seed.js
server/api/index.js
server/db/models/index.js

Reverts ans-graceshopper/spell-store#136 
accidentally deleted the whole file instead of lines...

Revert "Seed for orders"

---

script/seed.js

Added Sarah's seed file code and updated to include placeholder total for order

updated sarahs seed file to include total

---

client/components/lineItem.js
client/store/cart.js
server/api/cart.js
server/db/models/order.js

- Adjusted cart API routes to send back spell and spellorders through table attributes
- Changed cart reducer to have more specific actions
- fixed thunk names in map to dispatch for cart line item

cart quantities change live in chrome

---

client/components/cart.js
client/components/lineItem.js
client/components/navbar.js
client/store/cart.js
client/store/spell-detail.js
server/api/cart.js

- Cart is now in an HTML table with styling
- Cart spells link to spell detail page
- Cart reducer updated to fix add to cart action
- Clicking store name brings you to shop page

Cart css #143

---

client/components/spelldetail.js

Add to Cart button w/quantities now works on spell detail component

add to cart with quantities now working on spell detail page

---

client/components/allspells.js
client/components/user-order-lineitem.js

removed comment from user-order-lineitem
